// Court statistics stay at police-force-area level, independent of the incident grid.
const COURT=DATA.convictions;
let courtLayer=null, currentView='crime', courtLastTotal=0;
const $=id=>document.getElementById(id);
const courtForce=$('court-force'),courtScope=$('court-scope'),courtGroup=$('court-group'),courtOffence=$('court-offence'),courtCode=$('court-code');
function choices(element,values,allLabel,preserve=false){const prior=preserve?element.value:'*';element.replaceChildren();for(const [value,label] of [['*',allLabel],...values.map(v=>[v,v])]){const o=document.createElement('option');o.value=value;o.textContent=label; o.title=label;element.appendChild(o)}element.value=[...element.options].some(o=>o.value===prior)?prior:'*';}
function scopeRows(){return COURT.records.filter(r=>courtScope.value==='all'||r.indictable);}
function updateCourtChoices(level){let rows=scopeRows();if(level<=0)choices(courtGroup,[...new Set(rows.map(r=>r.group))].sort(),'All offence groups');if(courtGroup.value!=='*')rows=rows.filter(r=>r.group===courtGroup.value);if(level<=1)choices(courtOffence,[...new Set(rows.map(r=>r.offence))].sort(),'All offence subtypes');if(courtOffence.value!=='*')rows=rows.filter(r=>r.offence===courtOffence.value);if(level<=2)choices(courtCode,[...new Set(rows.map(r=>r.code))].sort(),'All detailed legal codes');}
function courtRows(includeForce=true){return scopeRows().filter(r=>(!includeForce||courtForce.value==='*'||r.force===courtForce.value)&&(courtGroup.value==='*'||r.group===courtGroup.value)&&(courtOffence.value==='*'||r.offence===courtOffence.value)&&(courtCode.value==='*'||r.code===courtCode.value));}
function marginal(rows,dimension){const counts={};for(const r of rows)for(const [label,count] of Object.entries(r[dimension]))counts[label]=(counts[label]||0)+count;return counts;}
function isUnknown(label){return /unknown|not (?:known|stated)|not applicable|not provided/i.test(label);}
function bars(target,title,counts,total,ordered=false){const wrapper=document.createElement('div');if(title){const heading=document.createElement('h3');heading.textContent=title;wrapper.appendChild(heading)}const entries=Object.entries(counts);const fiscal=['Apr-Jun','Jul-Sep','Oct-Dec','Jan-Mar'];entries.sort(ordered?(a,b)=>fiscal.includes(a[0])&&fiscal.includes(b[0])?fiscal.indexOf(a[0])-fiscal.indexOf(b[0]):a[0].localeCompare(b[0]):(a,b)=>(Number(isUnknown(a[0]))-Number(isUnknown(b[0])))||(b[1]-a[1]));if(!total){const p=document.createElement('p');p.className='court-help';p.textContent='No conviction occasions in this selection.';wrapper.appendChild(p)}for(const [label,count] of entries){const row=document.createElement('div');row.className='bar-row'+(isUnknown(label)?' unknown':'');const labelRow=document.createElement('div');labelRow.className='bar-label';const name=document.createElement('span');name.textContent=label;const number=document.createElement('span');number.textContent=fmt(count)+' · '+(total?100*count/total:0).toFixed(1)+'%';labelRow.append(name,number);const track=document.createElement('div');track.className='bar-track';const fill=document.createElement('div');fill.className='bar-fill';fill.style.width=(total?100*count/total:0)+'%';track.appendChild(fill);row.append(labelRow,track);wrapper.appendChild(row)}if(title&&total){const unknown=entries.filter(([label])=>isUnknown(label)).reduce((a,[,n])=>a+n,0);const p=document.createElement('p');p.className='court-help';p.textContent='Unknown / unspecified: '+fmt(unknown)+' ('+(100*unknown/total).toFixed(1)+'%).';wrapper.appendChild(p)}target.appendChild(wrapper);}
function breakdown(target,rows,field){target.replaceChildren();const counts={};for(const r of rows)counts[r[field]]=(counts[r[field]]||0)+r.total;for(const [name,count] of Object.entries(counts).sort((a,b)=>b[1]-a[1])){const button=document.createElement('button');button.className='breakdown-row';const label=document.createElement('span');label.textContent=name;const number=document.createElement('strong');number.textContent=fmt(count);button.append(label,number);button.addEventListener('click',()=>{if(field==='offence'){courtOffence.value=name;updateCourtChoices(2);}else{courtCode.value=name;}renderCourt();});target.appendChild(button)}}
function courtColour(count,max){if(!count)return '#cdd3cf';const t=max?Math.log1p(count)/Math.log1p(max):0;return t<.25?'#e8dba7':t<.5?'#e4a052':t<.75?'#ba4d32':'#641f29';}
function renderCourt(){if(!COURT)return;const rows=courtRows(),total=rows.reduce((a,r)=>a+r.total,0);courtLastTotal=total;$('court-total').textContent=fmt(total);$('court-selected').textContent=courtCode.value!=='*'?courtCode.value:courtOffence.value!=='*'?courtOffence.value:courtGroup.value!=='*'?courtGroup.value:'All selected offence groups';$('court-demographics').replaceChildren();bars($('court-demographics'),'Sex',marginal(rows,'sex'),total);bars($('court-demographics'),'Age at court proceedings',marginal(rows,'age'),total,true);bars($('court-demographics'),'Ethnicity',marginal(rows,'ethnicity'),total);if(courtScope.value==='all'){const note=document.createElement('p');note.className='court-help';note.textContent='Summary offences are included. Their ethnicity breakdown is not reliably reported; use the indictable view for ethnicity comparisons.';$('court-demographics').prepend(note)}$('court-detailed-ethnicity').replaceChildren();bars($('court-detailed-ethnicity'),null,marginal(rows,'detailed_ethnicity'),total);$('court-quarters').replaceChildren();bars($('court-quarters'),null,marginal(rows,'quarter'),total,true);breakdown($('court-subtypes'),rows,'offence');breakdown($('court-codes'),rows,'code');
const byForce={};for(const r of courtRows(false))byForce[r.force]=(byForce[r.force]||0)+r.total;const max=Math.max(0,...Object.values(byForce));$('court-map-key').textContent='Map: conviction occasions per force area for the selected offences. Logarithmic colour scale: 1–'+fmt(max)+'. Grey = no recorded convictions in the selection, or no separate published profile (City of London). Demographic charts use '+(courtForce.value==='*'?'all English force areas':courtForce.value)+'.';if(courtLayer)map.removeLayer(courtLayer);courtLayer=L.geoJSON(COURT.boundaries,{style:f=>{const force=f.properties.moj_name;return {color:force===courtForce.value?'#173b38':'#657a70',weight:force===courtForce.value?3:1,fillColor:courtColour(byForce[force]||0,max),fillOpacity:.4}},onEachFeature:(f,l)=>{const force=f.properties.moj_name,available=Object.hasOwn(COURT.metadata.area_counts,force);l.bindTooltip('<b>'+escapeText(force)+'</b><br>'+(available?fmt(byForce[force]||0)+' conviction occasions<br>Click to view demographic profile':'No separate published court profile'));if(available)l.on('click',()=>{courtForce.value=force;renderCourt()});}});if(currentView==='court')courtLayer.addTo(map);}
function switchView(view){if(view==='court'&&!COURT)return;currentView=view;$('crime-controls').hidden=view!=='crime';$('court-controls').hidden=view!=='court';$('crime-view').setAttribute('aria-pressed',String(view==='crime'));$('court-view').setAttribute('aria-pressed',String(view==='court'));document.querySelector('main').classList.toggle('court-view',view==='court');document.querySelector('h1 em').textContent=view==='crime'?'Recorded crime.':'Convicted persons.';$('month').textContent=view==='crime'?new Date(meta.month+'-01T12:00:00Z').toLocaleDateString('en-GB',{month:'long',year:'numeric'})+' · Recorded incidents':COURT.metadata.period_label+' · Court outcomes';map.closePopup();if(view==='court'){if(layer)map.removeLayer(layer);renderCourt()}else{if(courtLayer)map.removeLayer(courtLayer);render()}map.invalidateSize();map.fitBounds([[49.85,-6.5],[55.85,1.85]]);}
$('crime-view').addEventListener('click',()=>switchView('crime'));$('court-view').addEventListener('click',()=>switchView('court'));
if(COURT){choices(courtForce,Object.keys(COURT.metadata.area_counts).sort(),'All English force areas');updateCourtChoices(0);$('court-period').textContent='Separate regional dataset · '+COURT.metadata.period_label+'. No linkage to individual July 2026 crimes.';$('court-source').href=COURT.metadata.source_receipt.source;$('court-guide').href=COURT.metadata.technical_guide;$('court-attribution').textContent=COURT.metadata.boundary_attribution+' MoJ statistics: Open Government Licence v3.0.';map.attributionControl.addAttribution('Force boundaries: &copy; Crown copyright / ONS / OS 2024');courtScope.addEventListener('change',()=>{updateCourtChoices(0);renderCourt()});courtGroup.addEventListener('change',()=>{updateCourtChoices(1);renderCourt()});courtOffence.addEventListener('change',()=>{updateCourtChoices(2);renderCourt()});courtCode.addEventListener('change',renderCourt);courtForce.addEventListener('change',()=>{renderCourt();if(courtForce.value!=='*'){const l=courtLayer.getLayers().find(l=>l.feature.properties.moj_name===courtForce.value);if(l)map.fitBounds(l.getBounds(),{padding:[25,25]})}else map.fitBounds([[49.85,-6.5],[55.85,1.85]])});$('court-weapons').addEventListener('click',()=>{courtScope.value='indictable';updateCourtChoices(0);courtGroup.value='Possession of weapons';updateCourtChoices(1);renderCourt()});$('court-reset').addEventListener('click',()=>{courtForce.value='*';renderCourt();map.fitBounds([[49.85,-6.5],[55.85,1.85]])});}else{$('court-view').disabled=true;$('court-view').title='Generate this map with --convictions to enable regional profiles';}
